Dev(ccontrol): Support modify multiple tasks at one time
PKUHPC/CraneSched-FrontEnd pull request #111
Opened 2024-06-28 12:20 UTC by syrinka

2024-07-02 14:19 UTC, Nativu5 requested changes

2024-07-02 14:19 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +			updateJobCmd.Flags().StringVarP(&FlagTaskIds, "job", "J", "", "Specify job id of the job to be modified")
对应修改命令描述，参考其他命令中对逗号分隔列表形式的参数的描述。

2024-07-02 14:19 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +			var taskId uint32
这里初始化为 0

2024-07-02 14:19 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +				log.Tracef("Modifying task ID: %d", taskId)
对用户显示时，任务统一使用“job”而不用“task”。
另外是不是考虑一下参数的错误处理（假如输入不是数字）？

2024-07-09 05:10 UTC, RileyWen commented on internal/ccontrol/CmdArgParser.go
> +					if err := ChangeTaskTimeLimit(taskId, FlagTimeLimit); err != util.ErrorSuccess {
这不如改RPC

2024-07-09 05:10 UTC, RileyWen commented on internal/ccontrol/CmdArgParser.go
> +					if err := ChangeTaskTimeLimit(taskId, FlagTimeLimit); err != util.ErrorSuccess {
单个RPC发多个Task ID

2024-08-13 02:46 UTC, Nativu5 commented
Moved to #151.

2024-08-13 02:46 UTC, closed without merging