Origin/bugfix/ccontrol
PKUHPC/CraneSched-FrontEnd pull request #115
Opened 2024-07-05 11:10 UTC by jjxbw

2024-07-05 11:14 UTC, jjxbw commented
modify -help format in crun, calloc, cacctmgr; use regular expression for ccontrol update

2024-07-05 15:33 UTC, Nativu5 requested changes

2024-07-05 15:33 UTC, Nativu5 commented on internal/cacctmgr/CmdArgParser.go
> +				err = ModifyAccount("allowed-partition", strings.Join(FlagAccount.AllowedPartitions, ","), FlagAccount.Name, protos.ModifyEntityRequest_Overwrite)
ModifyAccount() 函数的第一个参数是和 Protobuf 以及后端相对应的，直接这样修改会出错。

2024-07-05 15:33 UTC, Nativu5 commented on internal/ccontrol/ccontrol.go
> +	re := regexp.MustCompile(`(.*)\[(\d+)-(\d+)\](.*)`)
有没有考虑过使用 internal/util 包里的 ParseHostList 和 ParseNodeList 呢？应该这两个函数处理起来更方便一些。

2024-07-05 15:33 UTC, Nativu5 commented on internal/crun/CmdArgParser.go
> +	rootCmd.Flags().StringVarP(&FlagJob, "job-name", "J", "", "Name of job")
如果能参考一下其他命令的 --help 完善一下翻译（比如 cbatch 和 cacctmgr、ccontrol 的 help）会比较好。

2024-07-08 12:43 UTC, jjxbw commented
一些显示类问题

2024-07-08 12:43 UTC, closed without merging