Dev/Modify multiple task
PKUHPC/CraneSched-FrontEnd pull request #151
Opened 2024-08-12 06:28 UTC by syrinka

`ccontrol update job` can submit multiple tasks at a time

2024-08-15 08:55 UTC, Nativu5 approved these changes

2024-08-15 08:55 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
>  	FlagTaskId         uint32
修改后，这个变量是否是冗余的？

2024-08-15 08:55 UTC, Nativu5 commented on internal/ccontrol/ccontrol.go
> +func SummarizeModification(reply *protos.ModifyTaskReply) util.CraneCmdError {
建议修改一下函数的名称，目前这个函数只接收 ModifyTaskReply，但是后续可能还会添加对 ModifyState 等 RPC 的 reply 的处理函数。

2024-08-15 08:55 UTC, Nativu5 commented on internal/ccontrol/ccontrol.go
> +		fmt.Printf("Job %s modified successfully.\n", modifiedTasksStr)
好像没必要 for 循环一下转成 string? 直接 %v 输出数组？

2024-08-15 08:55 UTC, Nativu5 commented on internal/ccontrol/ccontrol.go
> +		modifiedNodesStr := strings.Join(reply.ModifiedNodes, ",")
同上，似乎可以用 %v。

2024-08-15 08:55 UTC, Nativu5 commented on internal/util/string.go
> +			fmt.Println("Invalid job Id: " + taskIdStrSplit[i])
用 log.

2024-08-15 08:55 UTC, Nativu5 commented on internal/ccontrol/ccontrol.go
> +	taskIds, perr := util.ParseTaskIds(taskStr)
这里按照编码惯例应该用 taskIds, ok := ...

2024-08-15 08:56 UTC, Nativu5 requested changes
同上。

2024-08-15 09:12 UTC, syrinka commented on internal/ccontrol/CmdArgParser.go
>  	FlagTaskId         uint32
> 修改后，这个变量是否是冗余的？

show 命令还不支持一次查询多个任务，因此目前保留了 `FlagTaskId` 作语义上的区分

2024-08-15 09:24 UTC, syrinka commented on internal/ccontrol/ccontrol.go
> +		fmt.Printf("Job %s modified successfully.\n", modifiedTasksStr)
> 好像没必要 for 循环一下转成 string? 直接 %v 输出数组？

那这里是否也要一起改呢

https://github.com/PKUHPC/CraneSched-FrontEnd/blob/6f6e9442b80a28d3250eed348831485577287543/internal/ccancel/ccancel.go#L87-L102

2024-08-16 05:05 UTC, Nativu5 commented on internal/ccontrol/ccontrol.go
> +		fmt.Printf("Job %s modified successfully.\n", modifiedTasksStr)
这里可以一并改掉了。

2024-09-05 11:53 UTC, Nativu5 approved these changes

2024-09-05 11:54 UTC, merged