fix squeue format
PKUHPC/CraneSched-FrontEnd pull request #189
Opened 2024-10-14 08:47 UTC by 1daidai1

![image](https://github.com/user-attachments/assets/09ddac21-f555-412e-baca-40301ef66af0)

2024-10-14 11:28 UTC, Nativu5 requested changes

2024-10-14 11:28 UTC, Nativu5 commented on internal/cqueue/cqueue.go
> +	}
这不应该在  QueryTableOutput 里面判断。这是QueryTasksInfo调用者的事情。

2024-10-14 11:28 UTC, Nativu5 commented on internal/cqueue/cqueue.go
> +}
所以这个判断有意义吗？return err 不就行了。

2024-10-14 11:28 UTC, Nativu5 commented on internal/cwrapper/slurm.go
> +func SlurmQueryTableOutput(reply *protos.QueryTasksInfoReply) util.CraneCmdError {
全部改名。slurm.go 这个文件里面有所有 Slurm Wrapper 的函数，但是这几个函数都是 Squeue 用的，所以得区分开来。

2024-10-14 12:03 UTC, NamelessOIer commented on internal/util/string.go
> +}
Task 和 Job 建议统一下

2024-10-15 02:44 UTC, Nativu5 requested changes

2024-10-15 02:44 UTC, Nativu5 commented on internal/cwrapper/slurm.go
> +func SqueueQueryTableOutput(reply *protos.QueryTasksInfoReply) util.CraneCmdError {
Squeue 这些辅助函数应该开头小写，因为这个函数是 cwrapper 包内部的函数，不应该导出。

2024-10-15 02:45 UTC, Nativu5 commented
注意：https://github.com/PKUHPC/CraneSched-FrontEnd/pull/182 这个 PR 也需要修改。

2024-10-15 06:20 UTC, Nativu5 requested changes
基本没有问题了，还需要修改一下错误输出。

2024-10-15 06:20 UTC, Nativu5 commented on internal/cacct/cacct.go
> +			log.Errorln(err)
由于 error 类型结尾没有标点、开头不能大写，所以 log.Error 在输出时也不能直接输出 error 了。需要明确地告诉用户哪里出错了，比如：
```golang
log.Errorf("Invalid account list specified: %v.\n", err)
```
下同。

2024-10-16 03:46 UTC, Nativu5 requested changes

2024-10-16 03:46 UTC, Nativu5 commented on internal/cwrapper/slurm.go
> +							log.Errorln(err)
还有一部分错误提示没有修正

2024-10-16 03:46 UTC, Nativu5 commented on internal/cwrapper/slurm.go
> +		log.Errorln("Invalid time interval.")
这里最好在错误提示后面，log一下err。

2024-10-16 03:46 UTC, Nativu5 commented on internal/cacct/cacct.go
> +			log.Errorf("Invalid Qos list specified: %v.\n", err)
输出里面统一用 QoS 吧

2024-10-16 05:58 UTC, 1daidai1 commented on internal/cwrapper/slurm.go
> +		log.Errorln("Invalid time interval.")
已修改

2024-10-16 13:33 UTC, Nativu5 approved these changes

2024-10-16 13:34 UTC, merged