Feat: Modify log modular output
PKUHPC/CraneSched-FrontEnd pull request #203
Opened 2024-11-13 09:33 UTC by 1daidai1

![image](https://github.com/user-attachments/assets/71bec8fb-ce4d-4a78-a3ad-11f28eba2317)
注：
命令行默认不配置-n则修改的是控制节点；配置了-n则是计算节点；
eg：./ccontrol modify logger -n 44f19bdf69ff -m default -l error //只会进入craned逻辑
      ./ccontrol modify logger  -m default -l error //进入控制节点逻辑；

2024-11-13 09:34 UTC, 1daidai1 commented
后端https://github.com/PKUHPC/CraneSched/pull/341

2024-11-13 10:49 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +		Short: "Modify node logger log level",
这句英文什么意思？

2024-11-13 10:59 UTC, Nativu5 requested changes

2024-11-13 10:59 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +			if err := ChangeLoggerState(FlagNodeName, FlagLoggerName, FlagLogLevel); err != util.ErrorSuccess {
Logger 有什么 state？不应该是 Level 吗？

2024-11-13 10:59 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +
注意前面代码中没有空行。

2024-11-13 10:59 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +		updateCmd.AddCommand(updateLoggerCmd)
注意前面有空行

2024-11-13 10:59 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +			updateLoggerCmd.Flags().StringVarP(&FlagNodeName, "node-name", "n", "cranectld", "Specify names of the node to be modified(cranectld or real craned name)")
假如有个普通节点的名字就叫做 cranectld 呢？

2024-11-13 10:59 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +			updateLoggerCmd.Flags().StringVarP(&FlagLogLevel, "logger-level", "l", "trace", "Specify logger level")
1. 用语太冗余
既然已经在 ccontrol update logger 这个子命令中了，没必要每个选项都重复一遍，直接 -n node -c component -m module -l level 就可以了。
2. 不符合英语语法。
logger level 是什么？logging level 才是正确用法。

2024-11-13 11:17 UTC, Nativu5 requested changes

2024-11-13 11:17 UTC, Nativu5 commented on internal/ccontrol/ccontrol.go
>  			fmt.Printf("Nodes %v modified successfully.\n", reply.ModifiedNodes)
这块直接写串了吧。真的自己测试过吗？？？

2024-11-13 11:17 UTC, Nativu5 commented on internal/util/log.go
> +	}
假如用户配置一个名叫 cranectld 的计算节点就爆炸了

2024-11-14 01:47 UTC, 1daidai1 commented on internal/util/log.go
> +	}
不会crash,只会设置错误

2024-11-15 02:00 UTC, Nativu5 commented on protos/Crane.proto
> +  string log_level = 2;
logger
level

2024-11-15 02:04 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +			if err := ChangeLoggingLevel(FlagNodeName, FlagLoggerName, FlagLogLevel); err != util.ErrorSuccess {
默认情况下调用的是 ctld，最好添加一个 log.Info 提示一下用户。

2024-11-15 02:07 UTC, Nativu5 requested changes

2024-11-15 02:07 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +			updateLoggingLevelCmd.Flags().StringVarP(&FlagNodeName, "node-name", "n", "", "Specify names of the node to be modified( craned name, default: control node)")
Specify names of the node to be modified (craned names, unset for cranectld)

2024-11-15 02:11 UTC, Nativu5 requested changes

2024-11-15 02:11 UTC, Nativu5 commented on internal/ccontrol/CmdArgParser.go
> +			updateLoggingLevelCmd.Flags().StringVarP(&FlagNodeName, "node-name", "n", "", "Specify names of the node to be modified( craned name, default: control node)")
这几个 Flag 最好简略一点：
- node, n
- logger, m
- level, l

2024-11-15 06:14 UTC, Nativu5 commented
前端基本没有问题了。

2025-09-12 11:35 UTC, closed without merging