Added energy consumption collection plug-in
PKUHPC/CraneSched-FrontEnd pull request #211
Opened 2024-11-26 03:40 UTC by huyongqii

Node Monitor:
* IPMI Reader: IPMI is mainly used to collect power to calculate energy consumption.
* RAPL Reader: RAPL is mainly used to collect the energy consumption generated by the CPU.
* GPU Reader: GPU is mainly used to collect the energy consumption generated by GPU.
* SysLoad Reader: SysLoad is only used to collect system load related indicators.

Task Monitor:
* Cgroup Reader: Used to collect load indicators corresponding to tasks.
* GPU Reader: Used to collect the energy consumption of the GPU bound to the task.

2024-11-26 04:51 UTC, Nativu5 requested changes

2024-11-26 04:51 UTC, Nativu5 commented on plugin/energy/energy.go
> +	log.SetFormatter(&log.TextFormatter{
是不是可以考虑用 `nested-logrus-formatter`

2024-11-26 04:51 UTC, Nativu5 commented on plugin/energy/energy.go
> +	logDir := "/var/log/crane"
这个地方建议设置为 Config 可配置的，因为 Crane 的 Log 不一定在这个位置

2024-11-26 04:51 UTC, Nativu5 commented on plugin/energy/energy.go
> +		log.Info("\033[32m[EnergyPlugin]\033[0m Successfully set up logging to file")
全部都用 `\033[32m` 修饰会不会有些冗余？nested-logrus-formatter 应该支持终端高亮和模块化信息打印（例如 `[EnergyPlugin]`）：
```
log.WithField("component", "rest").Warn("warn message")
```

2024-11-26 04:51 UTC, Nativu5 commented on plugin/energy/energy.go
> +}
如果属于不关心的信息，直接留空即可，没有必要用反射判断一次。

2024-11-26 04:51 UTC, Nativu5 commented on plugin/energy/energy.go
> +	}
这个逻辑不太对，EndHook 是 **Ctld** 将任务 Running 状态变更为其他状态时才会触发。Ctld 触发的消息**只有**在 Ctld 节点上的 Plugind 才能接受到。而我们的 Energy 插件应该是在 Craned 上，因此这里不会产生预期效果。

2024-11-26 04:51 UTC, Nativu5 commented on plugin/energy/energy.go
> +func (p EnergyPlugin) Close() {
插件框架目前只是初步实现，很多 API 都没有，我们可能要讨论一下。

2024-11-26 04:51 UTC, Nativu5 commented on plugin/energy/energy.yaml
> +monitor:
样式最好和主仓库统一，我们其他的 Config 以驼峰为主：参考 etc/config.yaml

2024-11-26 04:51 UTC, Nativu5 commented on plugin/energy/pkg/monitor/task.go
> +	cgroupReader := cgroup.NewV1Reader(name)
可能得考虑一下搞个 Interface 抽象一下 Cgroup 数据接口

2024-11-26 07:16 UTC, huyongqii commented on plugin/energy/energy.go
> +	logDir := "/var/log/crane"
LGTM

2024-11-26 07:17 UTC, huyongqii commented on plugin/energy/energy.go
> +		log.Info("\033[32m[EnergyPlugin]\033[0m Successfully set up logging to file")
LGTM

2024-11-26 07:17 UTC, huyongqii commented on plugin/energy/energy.yaml
> +monitor:
LGTM

2024-11-26 07:17 UTC, huyongqii commented on plugin/energy/pkg/monitor/task.go
> +	cgroupReader := cgroup.NewV1Reader(name)
LGTM

2024-11-26 10:08 UTC, RileyWen commented on plugin/energy/pkg/cgroup/v1.go
> +	// 目前好像并未支持blkio控制器，所以IO统计数据为空
craned可以加 成本不高

2024-11-26 10:08 UTC, RileyWen commented on plugin/energy/pkg/types/types.go
下次开会讨论下这块data model的部分

2024-11-26 11:15 UTC, huyongqii commented on plugin/energy/pkg/types/types.go
好的

2024-11-26 11:24 UTC, huyongqii commented on plugin/energy/pkg/cgroup/v1.go
> +	// 目前好像并未支持blkio控制器，所以IO统计数据为空
好的，我了解下，后续增加下，这块有利于判断任务是否是IO密集型的

2024-11-27 06:24 UTC, L-Xiafeng commented on plugin/energy/pkg/cgroup/v1.go
> +		if fields[0] == "c" && strings.HasPrefix(fields[1], "195:") {
这里"195:"这些可以写个常量，换成用regex去匹配会不会好一些？

2024-11-27 06:24 UTC, L-Xiafeng commented on plugin/energy/pkg/cgroup/v1.go
> +	pattern := "/dev/nvidia[0-9]*"
要获取节点上所有gpu可以直接用nvml，要考虑下以后可能要支持昇腾的库

2024-11-27 06:24 UTC, L-Xiafeng commented on plugin/energy/pkg/gpu/reader.go
> +	count, err := nvmlDeviceGetCount()
nvmlDeviceGetCount这些可以做一层抽象，后面可能需要支持昇腾的库

2024-11-28 05:32 UTC, huyongqii commented on plugin/energy/pkg/gpu/reader.go
> +	count, err := nvmlDeviceGetCount()
LGTM

2024-11-28 05:32 UTC, huyongqii commented on plugin/energy/pkg/cgroup/v1.go
> +	pattern := "/dev/nvidia[0-9]*"
LGTM

2024-11-28 05:32 UTC, huyongqii commented on plugin/energy/pkg/cgroup/v1.go
> +		if fields[0] == "c" && strings.HasPrefix(fields[1], "195:") {
LGTM

2024-12-02 09:37 UTC, L-Xiafeng commented on plugin/energy/energy.go
> +	return "v1.0.0"
“1.0.0”就行

2024-12-02 09:37 UTC, L-Xiafeng commented on plugin/energy/energy.yaml
> +  switches:
换一个词吧，switch很怪

2024-12-02 09:37 UTC, L-Xiafeng commented on plugin/energy/pkg/cgroup/v1.go
> +	cmd := exec.Command("getconf", "CLK_TCK")
这个有包可以用吧，就不要用命令行了

2024-12-02 09:37 UTC, L-Xiafeng commented on plugin/energy/pkg/monitor/task.go
> +	log.Infof("Starting task monitor for task: %d, cgroup path: %s", taskID, taskName)
taskName改成其他名字

2024-12-02 09:37 UTC, L-Xiafeng commented on plugin/energy/pkg/monitor/task.go
> +	task.Start()
这里命名也改一下，不是task start，是Task的monitor start吧？

2024-12-02 12:59 UTC, huyongqii commented on plugin/energy/energy.yaml
> +  switches:
`switchs` -> `enabled` 如何？

2024-12-02 13:04 UTC, L-Xiafeng commented on plugin/energy/energy.yaml
> +  switches:
可以

2024-12-02 13:57 UTC, huyongqii commented on plugin/energy/pkg/monitor/task.go
> +	task.Start()
OK

2024-12-02 13:58 UTC, huyongqii commented on plugin/energy/pkg/monitor/task.go
> +	log.Infof("Starting task monitor for task: %d, cgroup path: %s", taskID, taskName)
OK

2024-12-02 15:10 UTC, Nativu5 requested changes

2024-12-02 15:10 UTC, Nativu5 commented on plugin/energy/energy.yaml
> +    taskBucket: "energy_task"
基本没问题了：
1. 这个配置文件中的一些值可能可以替换为占位符，例如 org 可以改为 YOUR_ORG_NAME 这种。
2. 这个配置文件和我们其他组件的配置格式（以及 Slurm 的风格）还是有些区别，建议改为首字母大写的驼峰式，例如 `BatchSize`, `FlushInterval`...

2024-12-02 15:10 UTC, Nativu5 commented on Makefile
> +plugin: energy-plugin other-plugins
我们统一一下 target name 吧：
- plugin-energy
- plugin-other
- plugin 是前两者

2024-12-03 07:36 UTC, huyongqii commented on plugin/energy/energy.yaml
> +    taskBucket: "energy_task"
OK，统一了格式

2024-12-03 07:36 UTC, huyongqii commented on Makefile
> +plugin: energy-plugin other-plugins
OK

2024-12-06 07:51 UTC, RileyWen commented on Makefile
> +CUDA_INCLUDE_PATH := /usr/include
改名叫PLUGIN_CGO_CLAGS 这种吧 因为只有一个plugin用了

2024-12-06 09:47 UTC, Nativu5 approved these changes

2024-12-06 09:54 UTC, huyongqii commented on Makefile
> +CUDA_INCLUDE_PATH := /usr/include
已完善

2024-12-11 10:27 UTC, Nativu5 commented
@huyongqii 如果没有问题，我们就合并了？

2024-12-11 10:28 UTC, huyongqii commented
> @huyongqii 如果没有问题，我们就合并了？

好的，我合并了

2024-12-11 10:28 UTC, merged