Add ceff cmd
PKUHPC/CraneSched-FrontEnd pull request #214
Opened 2024-12-03 03:05 UTC by 1daidai1

2024-12-03 03:12 UTC, 1daidai1 commented
后端hhttps://github.com/PKUHPC/CraneSched/pull/381

2024-12-03 08:01 UTC, Nativu5 requested changes

2024-12-03 08:01 UTC, Nativu5 commented on protos/Crane.proto
> +  rpc QueryTasksInfoByIds(QueryTasksInfoRequest) returns (QueryTasksInfoReply);
这个 RPC 的作用和 QueryTasksInfo 一样吧？有什么添加的必要吗？

2024-12-03 08:01 UTC, Nativu5 commented on internal/ceff/ceff.go
> +	taskJsonInfo := struct {
这边的匿名结构体提取出来，方便后续维护，然后 JSON 的 Tag Name，参考其他命令的输出格式。

2024-12-04 09:09 UTC, 1daidai1 commented on internal/ceff/CmdArgPaser.go
> +			}
已全部修改

2024-12-04 15:23 UTC, Nativu5 requested changes

2024-12-04 15:23 UTC, Nativu5 commented on internal/ceff/ceff.go
> +			log.Errorf("Error marshalling to JSON: %v", err)
这里不该直接返回吗？

2024-12-05 08:23 UTC, Nativu5 approved these changes

2024-12-05 08:23 UTC, merged