Dev/account multi op
PKUHPC/CraneSched-FrontEnd pull request #215
Opened 2024-12-03 08:03 UTC by huerni

2024-12-03 08:28 UTC, Nativu5 commented on internal/cacctmgr/CmdArgParser.go
> +				if err := BlockAccountOrUser("", protos.EntityType_Account, ""); err != util.ErrorSuccess {
感觉字符串分割这种工作，是不是在前端做好一些？

2024-12-03 08:35 UTC, huerni commented on internal/cacctmgr/CmdArgParser.go
> +				if err := BlockAccountOrUser("", protos.EntityType_Account, ""); err != util.ErrorSuccess {
也可以  可以改一下

2024-12-06 02:16 UTC, Nativu5 requested changes

2024-12-06 02:16 UTC, Nativu5 commented on internal/cacctmgr/cacctmgr.go
> +	var user_list []string
Golang 格式规范：驼峰式

2024-12-06 03:15 UTC, huerni commented on internal/cacctmgr/cacctmgr.go
> +	var user_list []string
写岔了

2025-02-16 06:02 UTC, closed without merging