Add specific reasons for failed task submission
PKUHPC/CraneSched-FrontEnd pull request #218
Opened 2024-12-10 08:38 UTC by 1daidai1

![image](https://github.com/user-attachments/assets/c177c348-8807-4612-b490-30205e277713)
![image](https://github.com/user-attachments/assets/836292e2-abff-461f-9750-a0acdf97be6a)
![image](https://github.com/user-attachments/assets/86aed349-2ae9-4e8e-900b-1edafb398c95)

2024-12-10 08:38 UTC, 1daidai1 commented
后端https://github.com/PKUHPC/CraneSched/pull/375

2024-12-19 09:09 UTC, 1daidai1 commented
已提交

2025-01-21 10:44 UTC, RileyWen commented on internal/cbatch/cbatch.go
> +			log.Errorf("Job allocation failed: %s.\n", util.ErrMsg(reason))
报错缺task id

2025-02-08 05:52 UTC, 1daidai1 commented on internal/cbatch/cbatch.go
> +			log.Errorf("Job allocation failed: %s.\n", util.ErrMsg(reason))
提交任务失败是不会分配任务id的
![image](https://github.com/user-attachments/assets/e0a93820-e0f7-4042-b140-3e0df9b74515)

2025-02-22 16:51 UTC, RileyWen commented
你这分支前后端不对应啊！！

2025-02-22 16:53 UTC, RileyWen commented on internal/util/err.go
>  	switch err_code {
然后这个一个switch 能搞定的 写了一堆switch  在干嘛

2025-02-23 07:21 UTC, Nativu5 requested changes

2025-02-23 07:21 UTC, Nativu5 commented on internal/cacctmgr/cacctmgr.go
> +		fmt.Printf("Delete account %s failed: %s.\n", name, util.ErrMsg(reply.GetCode()))
英文语法错误太多了，都一块改了吧。

2025-02-27 08:32 UTC, L-Xiafeng reviewed
没其他问题了

2025-02-27 08:32 UTC, L-Xiafeng commented on protos/PublicDefs.proto
> +  ERR_CODE_COUNT  = 67;
__ERR_CODE_COUNT

2025-02-27 14:32 UTC, Nativu5 approved these changes

2025-02-27 14:32 UTC, merged