supply cqueue/cinfo -o output
PKUHPC/CraneSched-FrontEnd pull request #228
Opened 2024-12-26 07:31 UTC by 1daidai1

2025-01-03 07:18 UTC, L-Xiafeng commented on internal/cqueue/cqueue.go
> +		// u-User, u-Uid, r-Reason, r-ReqNodes, x-ExcludeNodes, h-Held
这种都按字典序排一下吧

2025-01-03 07:26 UTC, L-Xiafeng commented
cacct的选项也对应补齐一下吧，然后这都有很多switch case，考虑下要不要用表驱动去做，不然看起来很麻烦

2025-01-04 08:36 UTC, L-Xiafeng commented
> cacct的选项也对应补齐一下吧，然后这都有很多switch case，考虑下要不要用表驱动去做，不然看起来很麻烦，对每一种做个format函数，这样以后改也方便。

以及上述所有新增/已有选项都要有对应的测试样例

2025-01-07 02:32 UTC, 1daidai1 commented
已处理

2025-01-09 09:53 UTC, L-Xiafeng commented on internal/cinfo/cinfo.go
> +			header = "Partition"
这些filed全都写一个format的函数吧，这样以后改起来也方便很多，然后这里的switch case就可以直接改成表驱动的实现了

2025-01-10 02:58 UTC, 1daidai1 commented on internal/cinfo/cinfo.go
> +			header = "Partition"
cinfo、cacct的参数缩写不一致，还有处理逻辑不一样，统一为一个函数个人任务没有必要，另外cinfo也改成表驱动模式

2025-02-15 15:47 UTC, Nativu5 requested changes

2025-02-15 15:50 UTC, Nativu5 commented
如果测试没有问题，功能方面应该没有其他问题了。另外麻烦看下 cacct 和 cqueue 两部分是否有可以复用的代码？

2025-02-17 02:46 UTC, 1daidai1 commented on internal/cacct/CmdArgParser.go
> +Fields are identified by a percent sign (%) followed by a character or string.
![image](https://github.com/user-attachments/assets/55f9a167-4f13-4f9b-90dc-bce19c32b1e7)

2025-02-17 02:46 UTC, 1daidai1 commented on internal/cacct/CmdArgParser.go
> +Each format specifier or string can be modified with a width specifier (e.g., "%.5j").
![image](https://github.com/user-attachments/assets/6831c7a4-fa1e-457e-b70c-0ce0157e1fd6)

2025-02-17 03:15 UTC, Nativu5 approved these changes

2025-02-17 06:31 UTC, merged